runtime: nodejs10

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

# Make warm up request to an new instance
inbound_services:
- warmup

automatic_scaling:
  target_cpu_utilization: 0.95
  max_instances: 1